### ISSUE TITLE
Runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by pushrbx** [Girbons/comics-downloader#121]
**Describe the bug**
App crashes with the following when I try to download `Tensei Shitara Slime Datta Ken` from `manganato`:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x7135ec]

goroutine 1 [running]:
github.com/anaskhan96/soup.findAllofem.func1(0x18?, {0xc0001a11d0?, 0x3, 0x3}, 0x80?)
        /Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:534 +0x1cc
github.com/anaskhan96/soup.findAllofem(0x0?, {0xc0001a11d0, 0x3, 0x3}, 0x0)
        /Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:538 +0xe4
github.com/anaskhan96/soup.Root.FindAll({0x0, {0x0, 0x0}, {0x8af120, 0xc00041e018}}, {0xc0001a11d0?, 0x3, 0x3})
        /Users/girbons/go/pkg/mod/github.com/anaskhan96/soup@v1.2.4/soup.go:283 +0x86
github.com/Girbons/comics-downloader/pkg/sites.MangaKakalotRetrieveIssueLinks({0x7f4c97, 0xd}, {0xc0000c0090, 0x24})
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/common.go:81 +0x514
github.com/Girbons/comics-downloader/pkg/sites.(*Manganato).RetrieveIssueLinks(0xc0000cde08?)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/manganato.go:31 +0x30
github.com/Girbons/comics-downloader/pkg/sites.LoadComicFromSource(0xc0000fabb0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/pkg/sites/loader.go:118 +0x3d2
github.com/Girbons/comics-downloader/cmd/app.download(0xc0000fabb0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:78 +0x312
github.com/Girbons/comics-downloader/cmd/app.Run(0xc0000fabb0)
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:125 +0x1c9
main.main()
        /Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/downloader/main.go:93 +0x26a
```
**To Reproduce**
Run the following on windows in a Powershell 6 terminal:
```
./comics-downloader.exe -url "https://manganato.com/manga-tz953334" -all -format=cbz -country en -custom-comic-name "Tensei Shitara Slime Datta Ken" -output "mangadwl"
```

**Expected behavior**
It should either start downloading properly, or state the problem what went wrong with a clear error message.

**Desktop**
 - OS: Windows 10
 - Version: 0.33.3
 - Type: CLI

**Comment by Girbons** [comment]
Hey @pushrbx I checked the error with the given url, the page does not exist.

> Expected behavior
It should either start downloading properly, or state the problem what went wrong with a clear error message.

Strongly agree! I'm planning to do that 😄
