### ISSUE TITLE
segfault in pre-built binary and locally compiled.

### ISSUE THREAD

**Issue by bdmorin** [Girbons/comics-downloader#62]
**Describe the bug**
My 20.04 system throws a segfault when starting to download (it appears). The binary appears to start up fine, then segfaults.

```
❯ ./comics-downloader 'https://www.comicextra.com/comic/invincible'   
INFO[0000] Downloading...                                url="https://www.comicextra.com/comic/invincible"
   0% |                                        |  [0s:0s]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x67bea9]

goroutine 1 [running]:
image/jpeg.Encode(0x8fde20, 0xc0010ce008, 0x0, 0x0, 0x0, 0x0, 0x8fd900)
	/usr/lib/go-1.13/src/image/jpeg/writer.go:576 +0x29
github.com/Girbons/comics-downloader/pkg/util.SaveImage(0x8fde20, 0xc0010ce008, 0x7fc05d748160, 0xc0010a0690, 0x8658d2, 0x3, 0x0, 0xb)
	/home/bdmorin/Projects/comics-downloader/pkg/util/util.go:171 +0x221
github.com/Girbons/comics-downloader/pkg/core.(*Comic).DownloadImages(0xc0001981b0, 0x7ffeee4174ef, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:262 +0x696
github.com/Girbons/comics-downloader/pkg/core.(*Comic).makePDF(0xc0001981b0, 0x7ffeee4174ef, 0x1, 0x0, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:119 +0xcd
github.com/Girbons/comics-downloader/pkg/core.(*Comic).MakeComic(0xc0001981b0, 0x7ffeee4174ef, 0x1, 0x100, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:291 +0xbe
github.com/Girbons/comics-downloader/cmd/app.download(0xc000193ee0, 0xc000103e00)
	/home/bdmorin/Projects/comics-downloader/cmd/app/downloader.go:90 +0x65f
github.com/Girbons/comics-downloader/cmd/app.Run(0xc000103ee0)
	/home/bdmorin/Projects/comics-downloader/cmd/app/downloader.go:125 +0x8c
main.main()
	/home/bdmorin/Projects/comics-downloader/cmd/downloader/main.go:83 +0x245
```
**To Reproduce**
I've tried with the stock binary and a self-compiled one. 

I've tried several urls, this one starts to work, but then fails. 
```
❯ ./comics-downloader  -all -format cbr -output ~/Files/comics -url 'https://www.comicextra.com/comic/the-boys'
INFO[0000] Downloading...                                url="https://www.comicextra.com/comic/the-boys"
 100% |████████████████████████████████████████|  [1s:0s]INFO[0007] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0009] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0010] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0011] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0012] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0013] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0014] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0016] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0017] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0018] CBR file correctly saved                     
 100% |████████████████████████████████████████|  [1s:0s]INFO[0019] CBR file correctly saved                     
   0% |                                        |  [0s:0s]panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x67bea9]

goroutine 1 [running]:
image/jpeg.Encode(0x8fde20, 0xc000904238, 0x0, 0x0, 0x0, 0x0, 0x8fd900)
	/usr/lib/go-1.13/src/image/jpeg/writer.go:576 +0x29
github.com/Girbons/comics-downloader/pkg/util.SaveImage(0x8fde20, 0xc000904238, 0x7f428000c840, 0xc0006ac660, 0x8658d2, 0x3, 0x0, 0xa)
	/home/bdmorin/Projects/comics-downloader/pkg/util/util.go:171 +0x221
github.com/Girbons/comics-downloader/pkg/core.(*Comic).DownloadImages(0xc0000e63f0, 0x7ffc815cc4b8, 0x1, 0x0, 0x0, 0x0, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:262 +0x696
github.com/Girbons/comics-downloader/pkg/core.(*Comic).makeCBRZ(0xc0000e63f0, 0x7ffc815cc4b8, 0x1, 0x0, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:170 +0x93
github.com/Girbons/comics-downloader/pkg/core.(*Comic).MakeComic(0xc0000e63f0, 0x7ffc815cc4b8, 0x1, 0xc0000e61b0, 0x0)
	/home/bdmorin/Projects/comics-downloader/pkg/core/core.go:289 +0x62
github.com/Girbons/comics-downloader/cmd/app.download(0xc000659ee0, 0x0)
	/home/bdmorin/Projects/comics-downloader/cmd/app/downloader.go:90 +0x65f
github.com/Girbons/comics-downloader/cmd/app.Run(0xc0000efee0)
	/home/bdmorin/Projects/comics-downloader/cmd/app/downloader.go:125 +0x8c
main.main()
	/home/bdmorin/Projects/comics-downloader/cmd/downloader/main.go:83 +0x245
```

**Expected behavior**
The URL downloads as expected and packages the download in the requested format.

**Desktop (please complete the following information):**
```
❯ neofetch --off 
bdmorin@phyzz 
------------- 
OS: Pop!_OS 20.04 LTS x86_64 
Host: Oryx Pro oryp5 
Kernel: 5.4.0-7634-generic 
Uptime: 7 hours, 50 mins 
Packages: 3645 (dpkg), 10 (brew), 30 (flatpak), 28 (snap) 
Shell: zsh 5.8 
Resolution: 2560x1080, 1920x1080 
DE: GNOME 
WM: Mutter 
WM Theme: Pop 
Theme: Pop-dark [GTK2/3] 
Icons: Pop [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i7-9750H (12) @ 4.500GHz 
GPU: Intel UHD Graphics 630 
GPU: NVIDIA GeForce RTX 2060 Mobile 
Memory: 10573MiB / 31827MiB 

❯ go version
go version go1.13.8 linux/amd64
```

**Additional context**
I'd like to help, but I'm out of my depth with segfaults.

**Comment by Girbons** [comment]
Hey @bdmorin, thanks for reporting this issue, I'll take a look asap!

**Comment by Girbons** [comment]
@bdmorin seems like `comicextra` has an issue with this comic, chapter's images are not there.
