### ISSUE TITLE
Segfault if no url parameter given

### ISSUE THREAD

**Issue by begss** [Girbons/comics-downloader#83]
```
$ ./comics-downloader
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x514304]

goroutine 1 [running]:
github.com/Girbons/comics-downloader/internal/logger.(*Logger).Error(0x0, 0x84b823, 0x19)
	/Users/girbons/go/src/github.com/Girbons/comics-downloader/internal/logger/customlogger.go:49 +0x44
github.com/Girbons/comics-downloader/cmd/app.Run(0xc0001122d0)
	/Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/app/downloader.go:112 +0xb4
main.main()
	/Users/girbons/go/src/github.com/Girbons/comics-downloader/cmd/downloader/main.go:80 +0x1b9
```

**Comment by Girbons** [comment]
Hi @begss, 

thanks for reporting, I'll release a fix soon!

**Comment by begss** [comment]
Thanks
